name: Docker Build & Push

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image (multi-platform)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: fanyucai1/scrna:latest