name: Docker Build & Push (Multi-platform)

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Free up disk space
      run: |
        echo "Before cleanup:"
        df -h
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get clean
        docker system prune -af || true
        echo "After cleanup:"
        df -h

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image (multi-platform)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: fanyucai1/scrna:latest