build-and-push:
  needs: check-dockerfile
  if: needs.check-dockerfile.outputs.changed == 'true'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v3
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build and Push amd64 Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Docker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: fanyucai1/scrna:latest
