name: Docker Build & Push (Multi-Arch No Cache)

on:
  push:
    branches:
      - main

jobs:
  check-dockerfile:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Dockerfile changes
        id: check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'Docker/Dockerfile'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  build-amd64:
    needs: check-dockerfile
    if: needs.check-dockerfile.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push amd64 Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: fanyucai1/scrna:amd64

  build-arm64:
    needs: check-dockerfile
    if: needs.check-dockerfile.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push arm64 Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Docker/Dockerfile
          platforms: linux/arm64
          push: true
          tags: fanyucai1/scrna:arm64

  manifest:
    needs: [build-amd64, build-arm64]
    if: needs.check-dockerfile.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Create and Push Multi-Arch Manifest
        run: |
          docker manifest create fanyucai1/scrna:latest \
            fanyucai1/scrna:amd64 \
            fanyucai1/scrna:arm64
          docker manifest push fanyucai1/scrna:latest